sigstore/helm-charts

charts/cosigned/Chart.yaml
charts/cosigned/README.md
charts/cosigned/templates/webhook/cosign_secret.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml
charts/cosigned/values.yaml

Support using a specific secret from the cluster as the cosign secret. 
Fixes the documentation to only store the public key instead of the private and cosign password.
Fixes https://github.com/sigstore/helm-charts/issues/29
```release-note
Add support to specific an existing secret key for cosign validations.
```

feat: support secret key ref

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/webhook/clusterrole_webhook.yaml

We missed to update the permissions in the cluster-role to be consistent with the code in sigstore/cosign. These permissions support fetching pull secrets attached to pod specs or their service accounts. 
Fixes https://github.com/sigstore/helm-charts/issues/25
```release-note
fix: add permissions to pull secrets attached to pod specs or their service accounts.
```

fix: missing permissions for image pull secrets

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/deployment.yaml
charts/rekor/templates/trillian-log-server/deployment.yaml
charts/rekor/templates/trillian-log-signer/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

when installing the rekor chart notice some pods are in crashloop
```
$ k get po
NAME                                         READY   STATUS             RESTARTS   AGE
rekor-mysql-756d7b8b4f-gcn82                 1/1     Running            0          2m11s
rekor-redis-6d5c5c99d8-5t8bn                 1/1     Running            0          2m11s
rekor-server-579c97969-zmffm                 0/1     CrashLoopBackOff   4          2m11s
rekor-trillian-log-server-7b659656bb-9pnp9   0/1     CrashLoopBackOff   4          2m11s
rekor-trillian-log-signer-c8ccc8cfc-8hsrk    0/1     CrashLoopBackOff   3          2m11s
```
this is because `trillian` needs the mysql be up and running to run and `rekor-server` needs `trillian` 
adding some init containers to perform the check before trying to start the …

rekor: wait for services to start to avoid crashloop

---

charts/rekor/Chart.yaml
charts/rekor/values.schema.json

This change allows the user to specify non-null values for storageClass for both MySQL and Rekor. Without this change, a schema validation error is thrown when any non-null value is supplied for either of these storageClass variables.
Fixes #31
```release-note
Fixed validation of non-default (non-null) storageClass values for the Rekor chart
```

rekor: Set storageClass types to string in schema

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/templates/trillian-log-server/deployment.yaml
charts/rekor/templates/trillian-log-signer/deployment.yaml
charts/rekor/values.yaml

The goal of this change is to upgrade curl to the current stable release. However, since the current stable release of curl behaves differently with respect to non-HTTP servers, a different solution was necessary for determining availability of the database (MySQL and MariaDB do not use HTTP).
This resulted in three changes:
1. Change the curl image to docker.io/curlimages/curl:7.79.1
2. Modify the test for database server availability to use netcat instead of curl
3. Refactor the initContainerImage section of the values.yaml to support multiple init containers
n/a
```release-note
rekor: refactored service wait init containers which includes a change to the structure of the initContainerImage section of values.yaml
```

rekor: refactor service wait init containers

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml

Remove unnecessary double quotes when using the `-secret-name` flag in cosigned
```
kubectl run nginx --image nginx -n my-namespace
Error from server (BadRequest): admission webhook "cosigned.sigstore.dev" denied the request: validation failed: secret "\"mysecret\"" not found: spec
```
Fixes
fixes: https://github.com/sigstore/helm-charts/issues/38
```release-note
```

[cosigned] fix: remove unnecessary double quotes

---

.github/workflows/release.yml
README.md
charts/cosigned/Chart.yaml
charts/rekor/Chart.yaml

Enabling OCI support for publishing Helm Charts to GitHub Container Registry

Added OCI support to release workflow

---

.github/workflows/release.yml
README.md
charts/cosigned/Chart.yaml
charts/rekor/Chart.yaml

Support for signing Helm releases and publishing to Rekor
Requires `GPG_PRIVATE_KEY` and `GPG_KEY_NAME` to be set as Secrets
CC: @SantiagoTorres @dlorenc We should also have some information about how to retrieve the public key and steps that can be used to validate the packages.

Support for signed released

---

charts/cosigned/Chart.yaml

- remove the v to make it semver compatible for OCI
Fixes https://github.com/sigstore/helm-charts/issues/54
```release-note
remove the v to make it semver compatible for OCI
```

remove the v to make it semver compatible for OCI

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/webhook/sa_webhook.yaml
charts/cosigned/values.yaml

This allows specifying annotations on the service account in the cosigned helm chart. This is needed to use workload identity with GKE.
```release-note
Added `.Values.webhook.serviceAccount.annotations` to allow specifying service account annotations
```

allow specifying annotations on service account

---

.github/dependabot.yml
.github/workflows/release.yml

- add dependabot
- update helm to v3.8.1
- set job permissions to push data to GitHub release and packages (related to https://github.com/sigstore/helm-charts/runs/5360536935?check_suite_focus=true)
n/a
```release-note
NONE
```

set job permissions to push data to GitHub release and packages 

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/service.yaml

Ingress service name `scaffold-rekor-server` does not match the service name of the rekor server which was `rekor`. Another option would be to change the helpers.tpl so the service name is `rekor.fullname` instead of `rekor.server.fullname`.
Fixes
```release-note
```

fix: ingress service name not found

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl

Do not trim trailing whitespace for conditional
server.logging.production, as it causes the value to be appended to the
previous line instead of the next.
Fixes
```release-note
```

Fix rekor chart lint error

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl

Fix typo, tagrgetPort => targetPort
Fix ternary, if .targetPort is empty, take .port, otherwise take .targetPort
Fixes
```release-note
```

Fix ternary logic for containerPorts

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/ci/ci-values.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/ingress.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Add separate property tlsEnabled to control population of tls fields.
Change existing tls type from object to array to mirror k8s ingress
schema. allowing multiple tls/hosts to be specified.
Fixes
```release-note
```

Allow specifying multiple hosts for service TLS

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.yaml

Prometheus scrap annotations should be on the pod and not the
deployment.
Also clean up some of the extra blank lines.
Fixes
```release-note
```

Move prometheus annotations from deployment to pod for Rekor.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/createtree-job.yaml
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Allow securityContext to be configurable.
Allow resources to be set on ctlog server
Allow specifying extraArgs for ctlog server
Split args on to multiple lines to make it more readable.
Fixes
```release-note
```

Make resources and securityContext configurable for ctlog helm chart

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/ci/ci-values.yaml
charts/fulcio/templates/_helpers.tpl
charts/fulcio/templates/createcerts-job.yaml
charts/fulcio/templates/fulcio-configmap.yaml
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/templates/fulcio-ingress.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml
charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/ingress.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

- allow specifying multiple container ports
- allow specifying multiple hosts/tls for ingress
- allow specifying ingress backend service name
- allow specifying deployment name
- allow specifying securityContext for create*jobs and deployment
- allow specifying resources for deployment
- allow specifying annotations for pods, for prometheus scrapping
- change json config to use toPrettyJson for readability
Fixes
```release-note
```

Allow customizing securityContext, resources, etc. for Fulcio

---

charts/ctlog/Chart.yaml

for some reason, the release for ctlog 0.2.3 is missing in the index.yaml but the release exists in Github
bumping the version to get a release out

bump ctlog to generate a new release

---

charts/fulcio/Chart.yaml
charts/fulcio/templates/createcerts-serviceacount.yaml
charts/fulcio/values.yaml

Add same condition for service account for as the job.
That is, guard if fileca for createcert for serviceaccount.
Fixes
```release-note
```

Dont create sa for createcert if no job for Fulcio

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Specify metrics port for ctlog
Allow specifying pod annotations.
Fixes
```release-note
```

Specify metrics port for ctlog

---

charts/trillian/Chart.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

Dont add initContainer to wait for MySQL when mysql.enabled != true.
Fixes
```release-note
```

Remove initContainer when mysql disabled

---

charts/fulcio/Chart.yaml
charts/fulcio/templates/_helpers.tpl
charts/fulcio/templates/fulcio-configmap.yaml
charts/fulcio/values.yaml

Due to the nature of helm handling of maps, it is not possible to
overwrite keys in the base value.yaml of the chart. Keys from value.yaml
included with the chart will always be present.
If it was the main chart, it would be possible to null existing keys,
but due to https://github.com/helm/helm/issues/9136, it does not work
with sub-charts at the moment.
So to allow downstream users to overwrite the config contents, the
default is now set in the template helper, when an empty object is
specified.
@nsmith5 what do you think about this solution? 
Fixes https://github.com/sigstore/helm-charts/issues/109
this addresses the issue https://github.com/sigstore/helm-charts/issues/109 without changing config.content to string type.
```release-note …
```

move default into template helper to allow overwrite.

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/configmap-sharding.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.yaml

Adds the sharding configmap as a helm template, which is a required configmap for rekor >= v0.6
```release-note
Update rekor chart to v0.6
```

Update rekor chart to v0.6

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml

The addition of the sharding configmap was under the file attestation
check, and would be excluded when local file attestation is disabled.
The fix move the inclusion of the sharding configmap to outside the file
attestation check.
Fixes
```release-note
```

Fix bug where configmap volume not mounted for rekor.

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Right now the CT log config has to be stored in a configmap. This PR also adds the option to store it in a Secret, leaving the ConfigMap as the default.
This will make it possible to store the config externally & use something like external-secrets to access the config. The config also stores the password for the ct log private key decryption, so it might make more sense in a Secret.

Add option to store CT log config in a secret

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/configmap.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

This is helpful for client who aren't using the `createtree` job and have a specific tree ID they want to use at install time.
Tested locally & this seems to work as expected.

Add option to specify tree ID in rekor configmap

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/policy-webhook/deployment_policy_webhook.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml

Fix/Add podAntiAffinity labels in cosigned deployments
**Checklist**

cosigned: Fix podAntiAffinity labels

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/policy-webhook/deployment_policy_webhook.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml

Double quotes were added twice  causing the following error:
`error retrieving webhook: mutatingwebhookconfiguration.admissionregistration.k8s.io \"\\\"cosigned.sigstore.dev\\\"\" not found"`
Fixes: https://github.com/sigstore/helm-charts/issues/165
**Checklist**

fix: webhook-name added multiple double quotes

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/crds/clusterimagepolicy.yaml

Add the new policy attestations fields to the CRD.
Fixes https://github.com/sigstore/helm-charts/issues/168
**Checklist**

cosigned: add policy fields to the CRD

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/policy-webhook/clusterrole_policy_webhook.yaml

Remove undefined apiGroups from the ClusterRole of the policy-webhook
Same as https://github.com/sigstore/cosign/pull/1896
**Checklist**

[cosigned] Remove undefined apiGroups from policy clusterrole

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/policy-webhook/deployment_policy_webhook.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml

1. Removes duplicated `terminationGracePeriodSeconds` field in the policy-webhook deployment
2. Increase `terminationGracePeriodSeconds` to 300s for the policy-controller, [ref](https://github.com/sigstore/cosign/blob/cf80511294b9f8cf3678dfc1e2584e5ee2ef6553/config/webhook.yaml#L98)
3. Removes duplicated `serviceAccountName` field in the policy-webhook deployment 
Fixes #163 
**Checklist**

Remove duplicated termination seconds in policy webhook and increase it for the controller

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Fix:
https://github.com/sigstore/helm-charts/issues/187
**Checklist**

allow specifying ctlog log prefix for ctlog chart.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/ctlog-configmap.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

treeID is handled the same way as rekor.
https://github.com/sigstore/helm-charts/blob/main/charts/rekor/templates/server/configmap.yaml#L14
Private key password is to set the key-password flag to the
createctconfig job.
https://github.com/sigstore/scaffolding/blob/main/cmd/ctlog/createctconfig/main.go#L60
**Checklist**

allow specifying existing treeID and private key password.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

fix ctlog private key type, null->string

---

charts/fulcio/Chart.yaml

bump fulcio for ctlog 0.2.24
Depends on #210 
**Checklist**

bump fulcio for ctlog 0.2.24

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/policy-webhook/clusterrole_policy_webhook.yaml
charts/policy-controller/templates/policy-webhook/deployment_policy_webhook.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

The replica field wasn't configurable via values.yaml
I used `helm schema-gen` plugin to generate the schema.
**Checklist**

chore: add replica field to be configurable

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/policy-webhook/deployment_policy_webhook.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

This PR adds a new field to the chart setting imagePullSecrets for the deployed services.
related to: https://github.com/sigstore/helm-charts/issues/231
**Checklist**

chore: set imagePullSecrets field

---

charts/trillian/Chart.yaml
charts/trillian/templates/_helpers.tpl

Right now the current parsing looks like this:
values.yaml
```yaml
logServer:
extraArgs:
- "--tracing=true"
```
it being evaluated as:
```yaml
- args:
- --storage_system=mysql
- --mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(MYSQL_HOSTNAME):$(MYSQL_PORT))/$(MYSQL_DATABASE)
- --rpc_endpoint=0.0.0.0:8090
- --http_endpoint=0.0.0.0:8091
- --alsologtostderr
- 0=--tracing=true
```
this should fix it

Update trillian template to correctly parse extra args

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.yaml

We can force the Job to create a new Trillian tree, which is useful for sharding.
ref https://github.com/sigstore/public-good-instance/issues/404

Add --force flag to rekor createtree Job for sharding

---

charts/updatetree/.helmignore
charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/ci/ci-values.yaml
charts/updatetree/templates/_helpers.tpl
charts/updatetree/templates/job.yaml
charts/updatetree/templates/namespace.yaml
charts/updatetree/templates/sa.yaml
charts/updatetree/values.schema.json
charts/updatetree/values.yaml

This can be used to mark old shards as FROZEN, or as ACTIVE if we ever need to rollback sharding.
**Checklist**

Add updatetree Helm Chart to mark old shards as frozen

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/policy-webhook/deployment_policy_webhook.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml

Corrections to handle permissions within Policy Controller
* Add `emptyDir` for ephemeral storage
* Set `HOME` environment variable so that all containers respect the `emptyDir` volume for ephemeral storage
* Correction to probes
Resolves #263

Adjustments to account for home directory and adjusting probe for Policy Controller

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/_helpers.tpl
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

Also bumps the prober version to latest.
Signed-off-by: Simon Kent <simek@google.com>

Expose write-prober flag through sigstore-prober helm-chart.

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Adds resources block to the createtree-job.
N.A.
Our cluster has some kyverno policies in place that requires to define resources on any object.
**Checklist**

Add resources to createtree-job

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/values.yaml

- bump policy controller images to use release v0.3.0
**Checklist**

bump policy controller images to use release v0.3.0

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/README.md.gotmpl
charts/trillian/values.yaml

Bumps the rekor and trillian images to most recent versions.
The current version of the rekor and trillian charts have an issue with the 
mysql and redis container both reporting following error.
```shell
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```
Bumping the images to latest versions at least resolves this.
> **Note**: Also included helm-docs template for rekor and trillian to ease updating the README.md. In values.yaml I also fixed some comments so they count as helm-docs to they show up in the README.md
**Checklist**

bump image versions for trillian

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

Add [CONTRIBUTING.md](https://github.com/marcofranssen/sigstore-helm-charts/blob/simplify-contributing/CONTRIBUTING.md) to ease contributions by community and having docs to point to when a PR does not comply with these guidelines.
Will also add the README.md.gotmpl templates for other charts once #297 and #299 are merged in this PR. Secondly I will ensure all charts have a lock file in place and committed.
Resolves #298 
**Checklist**

Add contributing.md with some guidelines

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml

Uses specified namespace rather than hardcoding `cosign-system` for CRD's webhook clientConfig.
Closes #311

policy-controller: use specified namespace for conversion webhook in CRD

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

- add createtree job annotation
that will allow us to add job annotations, and in the case of sigstore to add argocd annotations to address the issues described here https://github.com/sigstore/public-good-instance/issues/782
partially address https://github.com/sigstore/public-good-instance/issues/782
after we merge this will update argocd side

Add job extra annotations

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

add support for ttlSecondsAfterFinished for rekor createtree job

add support for ttlSecondsAfterFinished for rekor createtree job

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/createcerts-job.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

add support for ttlSecondsAfterFinished in fulcio createcerts Job

add support for ttlSecondsAfterFinished in fulcio createcerts Job

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

- update fulcio image to use release v0.6.0

update fulcio image to use release v0.6.0

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/deployment.yaml
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

Right now the [verification prober](https://github.com/sigstore/scaffolding/pull/390) is failing in staging due to an incorrect public key (`error running rekor write prober: rekor log public key not found for payload`). For verification in staging, we need to use the Rekor public key for the staging instance.
Cosign has a [couple of environment variables](https://pkg.go.dev/github.com/sigstore/cosign/pkg/cosign#GetRekorPubs) that can be used to configure this: `SIGSTORE_TRUST_REKOR_API_PUBLIC_KEY` and `SIGSTORE_REKOR_PUBLIC_KEY `. We could just add a flag to enable `SIGSTORE_TRUST_REKOR_API_PUBLIC_KEY`, but [during a slack discussion, Hayden mentioned that he would like to deprecate it](https://sigstore.slack.com/archives/C03R5G3CU2H/p1664572468492409).
This PR just adds an optional …

Add prober option to use alternative rekor public key

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/templates/createdb/serviceaccount.yaml
charts/trillian/values.yaml

Add a chart inside trillian for createdb which will initialize a Trillian DB schema.

Add chart for createdb job, bump trillian version.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffolding to depend on trillian 0.1.11.
fulcio/rekor changes are unrelated to this change, just looks like helm-docs was not run last time.

Bump trillian to 0.11, run helm-docs so picks up fulcio/rekor too.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Previously each key in the secret for ctlog was explicitly specified. But in order to support multiple Fulcios, they were moved to `fulcio-XXX` where XXX specifies the index we mount everything from the secret.
Also, we always write the config in secret, so there's no need to mount the config map anymore.
Relevant PRs from scaffolding:
This in particular:
https://github.com/sigstore/scaffolding/pull/352/files#diff-dc1ec6e1748d93e1822f7b79815b687dc9e2effb36adfc168dc1354b740164c0
https://github.com/sigstore/scaffolding/pull/334/files
https://github.com/sigstore/scaffolding/pull/341/files

Fix the secret mounting to work without specifying keys.

---

charts/tuf/Chart.yaml

in the PR https://github.com/sigstore/helm-charts/pull/307 it had two charts and one dependent on the other one, that break the release.
this PR fixes the first part to force a TUF release
will follow the release job to make sure that goes smoothly

force tuf release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.schema.json
charts/tuf/values.yaml

`scaffold` chart fails to use `tuf` as subchart as it does not allow `additionalProperties`, so we can specify `enabled` for the `tuf` subchart in `scaffold`
Explicitly add `enabled` as property to address this.
We can follow up whether we should set `additionalProperties` to `true` or `false` for schema validation as a follow up.

fix: add 'enabled' as property for subchart configuration

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Add optional additional volume configuration to policy-controller webhook deployment
Add additional vomues and volumeMounts options to allow for things such as CA Certs to be added to the policy-controller webhook deployment
Resolves #396
Validated in an environment with a mirrored sigstore-tuf-root that is available over https with a certificate signed by a custom Root CA. By mounting the custom root CA certificate under `/etc/ssl/certs` the mirror x509 cert can be trusted

policy-controller webhook deployment volumes

---

.github/workflows/test.yml

* Removing redundant step
* Rename workflow to match steps
Signed-off-by: Tahir Raza <1529130+tahirraza@users.noreply.github.com>
- Removing cosign install step as it was not being used.
- Updated the name of workflow `Lint Chart` -> `Test Chart`,  since it was doing `linting` plus ` install` of helm charts.
**Suggestion**: Perhaps, break down the workflow into separate `lint.yaml` and `e2e.yaml`.
None
Refactoring of test workflow
````bash
✔︎ ctlog => (version: "0.2.34", path: "charts/ctlog")
✔︎ fulcio => (version: "2.0.0", path: "charts/fulcio")
✔︎ policy-controller => (version: "0.3.4", path: "charts/policy-controller")
✔︎ rekor => (version: "1.0.0", path: …
```

Refactor GH workflows (#1)

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

This new version allows setting a new flag `--disable-tuf` as part of the extraArgs for the controller.

Bump policy-controller v0.4.2

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/backfillredis/backfill-job.yaml
charts/rekor/values.yaml

We need to run a job in the cluster to backfill redis. The code is here:
https://github.com/sigstore/rekor/pull/1163
So this wraps it in a helm chart

Backfillredis helm chart.

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

cc @pwelch @vaikas I think just putting the secret option under createctconfig might be easier, but wanted to make sure it'll work with the different shards?

Add createctconfig.secret option to ctlog helm chart

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

The ingress host name is required, so we should have a default value for the name since we have a default ingress rule.

Fix template error in rekor chart

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml
charts/trillian/values.schema.json
charts/trillian/values.yaml

Trillian: Add ability to specify custom storage system
Currently, the Trillian installation is hard-coded to use the mysql
storage system. While this is mostly fine (it is the most common and
used storage system for Trillian after all!), this makes it non trivial
to try custom backends for Trillian.
There is work on the way to introduce [a CockroachDB storage system for
Trillian](https://github.com/google/trillian/pull/2834). And, while this
is currently not usable using the mainline Trillian image, it is
possible to try out if one specifies a custom image for trillian.
To enable this, some variables were introduced:
* `storageSystem.driver`: defines the storage backend to use for both the log
signer and the log server. Defaults to `mysql`.
* `storageSystem.envCredentials`: is the …

Trillian: Add ability to specify custom storage system

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/_helpers.tpl
charts/policy-controller/templates/webhook/webhook_mutating.yaml
charts/policy-controller/templates/webhook/webhook_validating.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

This allows for more flexibility when setting up the namespace selector.
e.g. folks are able to set up whatever configuration they see fit for
their deployments.
This introduces two new components to the helmm chart:
* A `policy-controller.webhook.namespaceSelector` template which may be
leveraged as an `include` statement.
* A new key with the path `webhook.namespaceSelector` which allows for
configuring the aforementioned namespace selector.
The default is left as it was before, this way it won't affect new
deployments and upgrades will be seamless.

policy-controller: Make webhook namespace selector configurable

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/values.schema.json
charts/trillian/values.yaml

Similarly to the storage system, one is able to configure the quota
system with different drivers. This enables configuring that through
this helm chart.

Trillian: Make quota system configurable

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Signed-off-by: slimm609 <dbrian@vmware.com>
Allow CRDs to be skipped during the helm chart install. Helm has certain restrictions and issues with installing CRDs so allowing them to be installed independently of the helm chart is very common. https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
A common and documented approach is to use a different chart entirely.  https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts 
Allowing users to copy the CRD out of this chart and install as part of a separate chart and disable inside the policy-controller chart provides flexibility with the documented approach
n/a
This is a very common approach for multiple different charts and allowing policy-controller the …

Allow CRDs to be installed independently

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

- Limit trillian to amd64
- Bump trillian chart version to v0.1.16
Due to the toolbelt/netcat initContainer amd64 is the only supported architecture
Resolves #376

Limit trillian to amd64

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/ctlog-deployment.yaml

Previously there was a mismatch between the secret name between createctconfig job and the
server mounting that secret. Make them consistent.

consistent use of the ctlog secret between create job and server.

---

README.md
charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_images.tpl
charts/common/templates/_labels.tpl
charts/common/templates/_names.tpl
ct-install.yaml

Adds a common chart of reusable partials
#337

Added common chart

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/createtree-job.yaml

Adding ability to configure k8s resource requests and limits in all the components of ctlog.
At present, we cannot configure resource requests and limits for some components like one time jobs, initContainers and some deployments via Sigstore helm charts. This becomes a problem when `ResourceQuota` is defined for namespaces and prevents pods to spin up. It is a best practice to define resource requests and limits for all k8s resources.

Configure ctlog resources

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

- bump scaffold sql proxy and createdb to use release v0.6.2

bump scaffold sql proxy and createdb to use release v0.6.2

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

- bump scaffold to get new v0.2.2 trillian chart update

bump scaffold to get new v0.2.2 trillian chart update

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

Adding ability to configure k8s resource requests and limits in all the components of trillian.
At present, we cannot configure resource requests and limits for some components like one time jobs, initContainers and some deployments via Sigstore helm charts. This becomes a problem when `ResourceQuota` is defined for namespaces and prevents pods to spin up. It is a best practice to define resource requests and limits for all k8s resources.

Configure trillian resources

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/pvc.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

This change adds an option for setting the reclaim policy on the PVC used for storing the attestations for Rekor.
The default setting is 'Delete', which is also reflected in the configuration.
Hence, it's a non-breaking change.

feat: Add option for setting attestation storage PVC reclaim policy

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml

`webhook.securityContext.enabled` was not removed inside the security context of the deployment, which gave a warning. Omitting this key as with all other securityContexts.
None
None

Fix security context not omitting "enabled" key in policy-controller chart

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml

Fixes the following error returned by the policy-controller if securityContext is enabled in webhook:
```
Error: INSTALLATION FAILED: template: policy-controller/templates/webhook/deployment_webhook.yaml:135:31: executing "policy-controller/templates/webhook/deployment_webhook.yaml" at <toYaml>: wrong number of args for toYaml: want 1 got 2
```
Added in #483, but not noticed.

Fix securitycontext in deployment of webhook in policy-controller chart

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Bump chart to use latest release of Rekor

bump rekor to v1.1.0

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/pvc.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Removal of the field `persistentVolumeReclaimPolicy` from the Rekor server PVC as it is not a valid property on the resource
None
None

Remove reclaimPolicy from Rekor PVC

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/webhook/cleanup-leases.yaml

Add helm hook to pre-delete the leases.
closes https://github.com/sigstore/helm-charts/issues/504

policy-controller: add pre-delete hook

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

This adds `livenessProbe`/`readinessProbe` for the ctlog service.

Add probes for ctlog chart

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

This PR adds the ability to specify Fulcio's `--ct-log-url` flag.

Make Fulcio CT log configurable

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

- bump `gcr.io/cloudsql-docker/gce-proxy` to use release `v1.33.6`
- bump `gcr.io/trillian-opensource-ci/db_server` to release `v1.5.1`
Part of https://github.com/sigstore/public-good-instance/issues/1268

bump image gcr.io/cloudsql-docker/gce-proxy and gcr.io/trillian-opensource-ci/db_server

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

- bump scaffold to get image updates from trillian chart
Follow up of https://github.com/sigstore/helm-charts/pull/514
Part of https://github.com/sigstore/public-good-instance/issues/1268

bump scaffold to get image updates from trillian chart

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

Context: I added the Helm value `ct_log_url` in https://github.com/sigstore/helm-charts/pull/509. It relied on `ctlog.enabled` to control the output of the flag. This unfortunately doesn't work with the scaffold Helm chart, which sets `fulcio.ctlog.enabled=false`, which causes the ct_log_url to be set to an empty string, which is not the intent with that chart. This PR changes the behavior so that:
- If `disable_ct_log` is set to true, the flag is output as a blank string
- If `ct_log_url` is set, the output is the value
- Otherwise, the old behavior is preserved (assume CT Log running in cluster)
The `disable_ct_log` setting is added here because `ct_log_url` may not be set to an empty string as it would fail the boolean test, and that's a feature I would like personally.

Bugfix: Do not use ctlog.enabled to control ct-log-url flag

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

- bump fulcio to use release v1.3.1
https://github.com/sigstore/fulcio/releases/tag/v1.3.1

bump fulcio to use release v1.3.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

- bump scaffold to get fulcio chart release v1.3.1
follow up of https://github.com/sigstore/helm-charts/pull/525

bump scaffold to get fulcio chart release v1.3.1

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/_helpers.tpl
charts/policy-controller/templates/webhook/cleanup-leases.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Parametrize repository kubectl for policy-controller to possibility to choose private repository.

parametrize leases-cleanup repository

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

- update gce-proxy image to 1.33.8
Related to https://github.com/sigstore/public-good-instance/issues/1430

update gce-proxy image to 1.33.8

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/ci/ci-values.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/backendconfig.yaml
charts/rekor/templates/server/frontendconfig.yaml
charts/rekor/templates/server/ingress.yaml
charts/rekor/templates/server/service.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Adds ability to define more than one Ingress object for rekor, so we can launch GCE load balancer-based Ingress in parallel with NGINX one for testing in preparation for eventual migration

add ability to have multiple ingress objects for rekor, supporting GCE lb

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Needs https://github.com/sigstore/helm-charts/pull/555 to merge first

bump scaffold chart to reflect new rekor chart version

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.schema.json
charts/trillian/values.yaml

Switch to chainguard/netcat image for multiarch support (amd64 and arm64)
Fixes: #500 
#500

trillian: switch to chainguard/netcat

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/service.yaml

reimplement break in range w/i rekor service template

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json

add ability to set TLS fields for GRPC via k8s secret

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

- update image gcr.io/cloudsql-docker/gce-proxy to 1.33.9
Related to: https://github.com/sigstore/public-good-instance/issues/1534

update image gcr.io/cloudsql-docker/gce-proxy to 1.33.9

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml
charts/trillian/values.yaml

moves to v2 version of https://github.com/GoogleCloudPlatform/cloud-sql-proxy for the trillian chart
adds support for using unix domain sockets to provide connectivity between containers instead of TCP
also adds support for other command line arguments, which enables environment specific features like structured logging, health checks, etc

move to v2 of cloud-sql-proxy for trillian chart

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/poddisruptionbudget.yaml
charts/policy-controller/values.yaml

Adds a PodDisruptionBudget for the webhook deployment
Enhances availability, especially when using multiple replicas

feat: add pdb to policy-controller

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/config-sigstore-keys.yaml
charts/policy-controller/templates/webhook/configmap-clusterimagepolicy.yaml
charts/policy-controller/templates/webhook/configmap-policy-controller.yaml
charts/policy-controller/templates/webhook/configmap.yaml
charts/policy-controller/templates/webhook/cosign_secret.yaml
charts/policy-controller/templates/webhook/secret_certs_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Add common annotations variable inside values.yaml. If enabled, this will add those annotations to configmaps and secrets. Use case. Disable versioning in configmaps and secrets to avoid issues when policy controller helm chart is deployed using spinnaker.

fix: Add common annotations to cms/secrets. Avoid spinnaker issue with versioning

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

Change kubectl image tag to latest-dev, for cleanup-leases batch job.
Issue when using latest tag:
`failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown. `

fix: fix issue with kubectl latest tag image

---

charts/scaffold/Chart.yaml
charts/scaffold/templates/clusterrole.yaml

If you look in `rolebindings.yaml` alongside this file you will see that the way this role is consumed is via this templated name, but the name isn't actually templated!
N/A
N/A

Fix `ClusterRole` name to be based on SA name

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/templates/mysql/deployment.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

add securityContext to init and regular containers - trillian

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober to 0.6.9

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/deployment.yaml

set TUF_ROOT since homedir for nonroot image doesn't exist

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree for 0.6.10 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.schema.json
charts/tuf/values.yaml

Corrected secrets projected into tuf
https://github.com/sigstore/scaffolding/issues/873

Fixed tuf secrets path

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/values.schema.json
charts/scaffold/values.yaml

Tuf chart has been updated to version 0.1.9 to resolve a bug in the default path of sigstore PKI secrets (links below). Tuf new version has been updated in the scaffold chart, however the default values of the scaffold chart were not updated. This PR fixes the default value (which otherwise override the previous fix, unless one knows about it :)
* closes https://github.com/sigstore/helm-charts/issues/678
* also relates to:
- https://github.com/sigstore/scaffolding/issues/873
- https://github.com/sigstore/helm-charts/issues/670

fix: scaffold tuf secret paths default values

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for scaffolding v0.6.14 release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/templates/mysql/deployment.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml
charts/trillian/values.schema.json
charts/trillian/values.yaml

Signed-off-by: Karl Haworth <karl.haworth@aa.com>
Adding image pull secrets to additional charts
N/A
Similar to https://github.com/sigstore/helm-charts/pull/677
Following the existing pattern from other charts, add image pull secrets for private registries.

Add Image Pull Secrets to Trillian

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/createcerts-job.yaml
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

Adding image pull secrets to additional charts
N/A
Similar to https://github.com/sigstore/helm-charts/pull/677
Following the existing pattern from other charts, add image pull secrets for private registries.

Add image pull secrets to fulcio

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for v0.6.17 scaffolding release

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for v0.6.17 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v0.6.17 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.6.17 scaffolding release

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/configmap.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Expose webhook loglevel to Helm chart
```
❯ ct lint                                                          
policy-controller => (version: "0.6.8", path: "charts/policy-controller")
"sigstore" already exists with the same configuration, skipping
Linting chart "policy-controller => (version: \"0.6.8\", path: \"charts/policy-controller\")"
Checking chart "policy-controller => (version: …
```

Expose webhook loglevel to Helm chart

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/mysql/deployment.yaml
charts/rekor/templates/mysql/pvc.yaml
charts/rekor/templates/mysql/secret.yaml
charts/rekor/templates/mysql/service.yaml
charts/rekor/templates/mysql/serviceaccount.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Follow the pattern used by trillian, which can either manage its own database container or connect to a GCP SQL instance. If a container is created, the trillian mysql image is reused for convenience.

Add support for search_index params in rekor chart

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/createtree-job.yaml
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

```
ctlog => (version: "0.2.53", path: "charts/ctlog")
------------------------------------------------------------------------------- …
```

adds tolerations, nodeSelector, and affinity to ctlog.

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/templates/deployment.yaml
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

```
sigstore-prober => (version: "0.0.23", path: "charts/sigstore-prober") …
```

adds tolerations, nodeSelector, and affinity to sigstore-prober.

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/values.schema.json
charts/trillian/values.yaml

```
trillian => (version: "0.2.23", path: "charts/trillian")
------------------------------------------------------------------------- …
```

adds tolerations, nodeSelector, and affinity to trillian.

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/templates/job.yaml
charts/updatetree/values.schema.json
charts/updatetree/values.yaml

```
updatetree => (version: "0.0.10", path: "charts/updatetree")
--------------------------------------------------------------------- …
```

adds tolerations, nodeSelector, and affinity to updatetree.

---

charts/tuf/Chart.yaml
charts/tuf/templates/deployment.yaml
charts/tuf/values.schema.json
charts/tuf/values.yaml

```
tuf => (version: "0.1.13", path: "charts/tuf")
----------------------------------------------------------------------------------- …
```

adds tolerations, nodeSelector, and affinity to tuf.

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

It is best practice to configure resources for all containers and they are mandatory for a namespace configured with resource quota. This change adds the ability to configure resources for rekor initContainer `wait-for-trillian-log-server`

feat: Add ability to configure resources for rekor initContainer

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/templates/copy-secrets-job.yaml
charts/scaffold/values.schema.json
charts/scaffold/values.yaml

```
scaffold => (version: "0.6.51", path: "charts/scaffold")
---------------------------------------------------------------------------------------------------- …
```

adds tolerations, nodeSelector, and affinity to scaffold.

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml

closes https://github.com/sigstore/helm-charts/issues/696 . . . for real this time. 😅 
adds tolerations, nodeSelector, and affinity to createdb-job...correctly.
- https://github.com/sigstore/helm-charts/issues/696
- [original pull request](https://github.com/sigstore/helm-charts/pull/757)
```
trillian => (version: "0.2.25", path: "charts/trillian")
"sigstore" already exists with the same …
```

fixes tolerations, nodeSelector and affinity indention for trillian createdb job

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for 0.7.5 scaffolding release

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-configmap.yaml
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

It adds support for yaml format on fulcio config.
It algo expects that the config has a property called `format` defining if it is a `yaml` or a `json`. To avoid any breaking changes, if the field is not set, the json format and defaults are used.

Adding support for yaml on fulcio config

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/templates/copy-secrets-job.yaml

While `.cluster.local` is the standard suffix, it is configurable and not necessarily accurate.
Just using `.svc` and relying on ndots it used elsewhere through the helm chart, so drop the qualification here.
N/A
N/A

Drop the `.cluster.local` suffix

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/_helpers.tpl
charts/fulcio/templates/fulcio-configmap.yaml
charts/fulcio/templates/fulcio-deployment.yaml

I noticed that [this](https://github.com/sigstore/helm-charts/blob/b0a2dc97ee241bf1ab8b01726a48261108610df0/charts/fulcio/templates/fulcio-configmap.yaml#L16) condition was not working properly when I was bumping the fulcio version in scaffold.
Then I managed to move the logic of create the config with yaml format into the helper and setting the indent correctly.

Create helper for fulcio config yaml

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Add the ability to customize annotations on Policy Controller pods.
Fixes #766

Enable custom annotations in Policy Controller pods

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

*Note: This pull request was split out from [PR 831](https://github.com/sigstore/helm-charts/pull/831).*
This commit adds support for AWS KMS keys to the rekor chart. The following variables were added:
- `kmsType` - The KMS type (e.g., `aws`)
- `awsKmsCredentialsSecretName` - The name of an existing Kubernetes secret containing the IAM credentials to authenticate with AWS KMS
- The secret should contain two key value pairs: `accessKeyId` and `secretAccessKey`
- `awsKmsRegion` - The AWS region string where the KMS key is hosted
Users must set `kmsType` to the value `aws` in order to use this feature.
N/A
I tested these changes using a privately-hosted Sigstore instance. To use AWS KMS keys, users will need to supply the following changes via the values files:
- Set `kmsType` to `aws` in …

rekor: Added support for AWS KMS settings.

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

This commit adds support for AWS KMS keys to the fulcio chart. The following variables were added:
- `kmsType` - The KMS type (e.g., `aws`)
- `awsKmsCredentialsSecretName` - The name of an existing Kubernetes secret containing the IAM credentials to authenticate with AWS KMS
- The secret should contain two key value pairs: `accessKeyId` and `secretAccessKey`
- `awsKmsRegion` - The AWS region string where the KMS key is hosted
Users must set `kmsType` to the value `aws` in order to use this feature.
N/A
I tested these changes using a privately-hosted Sigstore instance. To use AWS KMS keys, users will need to supply the following changes via the values files:
- Set `kmsType` to `aws` in values.yaml
- Set `certificateAuthority` to a `kmsca` in values.yaml
- Set `kms_resource` to a …

fulcio: AWS KMS support

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for v0.7.11 scaffolding release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for v0.7.11 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v0.7.11 scaffolding release

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/templates/_helpers.tpl
charts/scaffold/templates/clusterrole.yaml
charts/scaffold/templates/copy-secrets-cronjob.yaml
charts/scaffold/templates/copy-secrets-job.yaml
charts/scaffold/values.schema.json
charts/scaffold/values.yaml

closes https://github.com/sigstore/helm-charts/issues/791
This PR adds a cronJob in conjunction w/ the copy secrets job.
- https://github.com/sigstore/helm-charts/issues/791
I included the secret `delete` permission due to the following error:
`Error from server (Conflict): Operation cannot be fulfilled on secrets "<secret_name>": the object has been modified; please apply your changes to the latest version and try again`
^ When trying to apply changes to secrets, I would receive the patch permission error about the resource version. This happens when the resource version of the secret being patched does not match the current resource version stored (e.g. used to manage optimistic concurrency). So if the secret has been modified since retrieved, the resource version will no longer match, …

adds optional cronJob to copySecretJob to avoid stale secrets.

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/templates/webhook/poddisruptionbudget.yaml
charts/policy-controller/templates/webhook/secret_certs_webhook.yaml
charts/policy-controller/templates/webhook/service_webhook.yaml

This PR fixes the issue where only the key is output when the value is not provided for some fields such as `.Values.annotations` and `.Values.webhook.podDisruptionBudget.maxUnavailable`.
The state in which only the key is output, such as `annotations: `, is not syntactically correct in yaml, so lint tools such as kubeconform output an error.
In this PR, the position of the conditional branch has been slightly changed so that if value is not specified, key is also not output.
`$ helm install policy-controller sigstore/policy-controller  -n policy-controller  --dry-run > old.yaml`
`$ helm install policy-controller ./charts/policy-controller -n policy-controller  --dry-run > new.yaml`
`$ dyff between .\old.yaml .\new.yaml`
old.yaml:
```yaml
...
apiVersion: policy/v1
kind: …
```

policy-controller: fix empty values

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl

ctlog chart expected extraArgs as a map instead of a list of strings; this makes it consistent with others

handle extraArgs consistently in ctlog chart as in other charts

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for ctlog update

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/templates/deployment.yaml
charts/tuf/values.schema.json
charts/tuf/values.yaml

This pull request adds support for customizing the following values in the tuf `Deployment` resource:
- Container resources
- Container security context
- Deployment security context
This work was originally implemented in pull request #460 which is unmerged. This current pull request supersedes Vipul's work.
I think I modified the `values.schema.json` correctly?

tuf: Support deployment resources customization

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for v0.7.18 release

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Expose `affinity` via `values.yaml` for the Webhook
Supports #814
I have the policy controller webhook deployed to my cluster, and have noticed that both replicas are on the same node. This is due to the `preferredDuring...` setting in the default affinity. I would also like to prefer different AZs, and `require` different nodes. To do this the user must be able to configure the affinity settings manually.

Expose webhook affinity via values.yaml

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/policy_webhook_configurations.yaml
charts/policy-controller/templates/webhook/webhook_mutating.yaml
charts/policy-controller/templates/webhook/webhook_validating.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Adds optional timeout values. The chart creates 4 webhook configuration objects (2 `ValidatingWebhookConfiguration` and 2 `MutatingWebhookConfiguration`. These are all created with the default `timeoutSeconds` ([docs](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts)) set to 10s. In some cases this is excessive (Kuberentes docs recommend this value to be as short as possible). In other cases user experience the need for longer timeouts, up to 20 seconds. This PR allows users to specify a specific timeout for each of the 4 configurations.
see for instance https://sigstore.slack.com/archives/C03096V09F1/p1737372057769759

feat: add webhook timeout values

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for 1.6.6 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json

supports specifying a Cloud SQL IAM username which requires a different DSN and cloud-sql-proxy command line argument

add support for cloud sql IAM user in rekor chart

---

.github/workflows/check-schema-policy-controller.yml
charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.schema.json

This PR removes 2 keys from the chart schema that were added by mistake in https://github.com/sigstore/helm-charts/commit/142e34b90583c3371baf069e8a8b0874ba9381c6 (probably through the [helm-schema](https://github.com/dadav/helm-schema), see https://sigstore.slack.com/archives/C03096V09F1/p1737627750048369):
* `additionalProperties`
* `required`
`helm-schema` gives for granted that all values in the `values.yaml` are required and should not allow additionalProperties, which is pretty inflexible. We should ask users to run `helm-schema -k additionalProperties,required` to avoid this from happening again. The PR also adds a new CI [workflow](https://github.com/sigstore/helm-charts/actions/workflows/check-schema-policy-controller.yml) to check that the schema has been generated with these …

fix: policy controller chart schema

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/templates/createdb/createdb-job.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

allow specifying SQL IAM username as argument

update trillian chart for iamUsername

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/cleanup-leases.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

this PR adds the following optional values, which allows to easily follow Kubernetes best practices/provide more flexibility
* leases cleanup job:
* deployment webhook:
Proof of work
```bash
helm template . \
--set webhook.envFrom.configmaps={cm1} \
--set 'webhook.envFrom.secrets={secr1,secr2}' \
--set webhook.priorityClass=critical \
--set webhook.automountServiceAccountToken=true \
--set leasescleanup.priorityClass=critical \
--set leasescleanup.automountServiceAccountToken=false \
--set leasescleanup.podSecurityContext.enabled=false \
--set leasescleanup.podSecurityContext.runAsUser=12345 \
--set leasescleanup.resources.requests.memory=12345Mi \
--set leasescleanup.resources.limits.cpu=12345m \
| grep -C 3 'leases-cleanup\|deployment_webhook.yaml\|cm1\|secr1\|secr2\|critical\|automountS …
```

feat: quality of life optional values to leases-cleanup job and webhook deployment

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for 0.7.21 scaffolding release

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/deployment_webhook.yaml

In https://github.com/sigstore/helm-charts/pull/894, the `envFrom` field was introduced in the values file, but its format is incorrect, resulting in the following error.
```
STDERR:
W0312 10:58:39.902314   15451 warnings.go:70] unknown field "spec.template.spec.containers[0].envFrom[0].name"
Error: UPGRADE FAILED: cannot patch "policy-controller-webhook" with kind Deployment: Deployment.apps "policy-controller-webhook" is invalid: spec.template.spec.containers[0].envFrom: Invalid value: "": must specify one of: `configMapRef` or `secretRef`
```
As stated in the [official documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables), the `name` field of `configMapRef` and …

Fix invalid field path for configMapRef and secretRef in envFrom

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/templates/tsa-configmap.yaml
charts/tsa/values.yaml

we're seeing https://github.com/argoproj/argo-cd/issues/15566 now because an empty value in a config map gets removed but introduces never-ending sync loop in argo

tsa: don't print null values into config map

---

README.md
charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/templates/tsa-deployment.yaml
charts/tsa/values.yaml

There's nothing urgent here but it allows removing `GOOGLE_APPLICATION_CREDENTIALS` from public good instance scaffold.
* tsa
*  Don't hard code GOOGLE_APPLICATION_CREDENTIALS. I left the env variable in there since I think it may be useful in other use cases
* remove a bit of repetition in tsa-deployment
* bump version
* README: Add missing charts
Fixes #940

TSA: remove hardcoded credentials file

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/_helpers.tpl
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

bump prober to v0.7.22, support probing tsa

---

.github/dependabot.yml

[previous approach with glob didn't sit well](https://github.com/sigstore/helm-charts/actions/runs/14431885758/job/40467638371) with ol' dependabot

specify each chart independently for dependabot

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.schema.json
charts/trillian/values.yaml

This changes the values schema for `trillian.storageSystem.envCredentials` to a more suitable type.
N/A
This var is rendered as the `env:` for the `trillian-log-signer` and `trillian-log-server` deployments. The default value is something like this: https://github.com/sigstore/helm-charts/blob/main/charts/trillian/templates/_helpers.tpl#L354-L377. It used to be able to be done in previous versions when there was no strict typing.

trillian: values schema for envCredentials to be an array

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian for v0.7.23 scaffolding release

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog for v0.7.23 scaffolding release

---

.github/workflows/test.yml
charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/templates/_helpers.tpl
charts/rekor-tiles/templates/deployment.yaml
charts/rekor-tiles/values.yaml

In GCP deployments, gRPC requires a TLS connection. This PR adds a volume to store TLS files, which for the public deployment will come from an ExternalSecrets config.

Add optional gRPC TLS certificate and key for rekor-tiles

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/values.yaml

A minor change to bump the Tessera library to pick up garbage collection of unneeded partial tiles.

Bump rekor-tiles to v0.1.6

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl

`forceMaster` value stays `true` even when set to `false` in Trillian's values.yaml
Workaround is to include `--force_master=false` in `extraArgs`

Trillian: fix log signer forceMaster always true

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/_helpers.tpl
charts/trillian/values.schema.json
charts/trillian/values.yaml

Add `etcdServers` to values.yaml for high availability log signer setup
Workaround is to include `--etcd_servers` in `extraArgs`

trillian: add log signer etcd servers to values

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/_helpers.tpl

This changes the logic for how redis.hostname is set. Either Redis is deployed via K8s, at which point the hostname is either set to the fullname by default or the provided hostname, or Redis is externally managed at which point the hostname is set to the provided hostname. The flags to Rekor will only be set when hostname is not empty, so they will not be set if Redis is disabled or an empty hostname is provided, which is the default.

Conditionally set Rekor Redis argument flags

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/trillian-log-signer/rbac.yaml

the hardcoded names previously used caused an overlap when multiple versions of the same chart were deployed into the same namespace.

make rbac object names unique
