sigstore/helm-charts

LICENSE
README.md
charts/rekor/Chart.yaml
charts/rekor/values.yaml

* Added LICENSE
* Updated README with details about the chart repository
* Added description to rekor chart
* Upgrade to Rekor server `v0.3.0`

Added license and various other enhancements

---

.github/workflows/release.yml
.github/workflows/test.yml

Trigger workflows only when changes occur to `charts` directory

Specify paths to trigger workflows

---

charts/cosigned/Chart.yaml
charts/cosigned/templates/webhook/configmap.yaml
charts/cosigned/templates/webhook/deployment_webhook.yaml
charts/cosigned/templates/webhook/service_monitor_webhook.yaml
charts/cosigned/templates/webhook/service_webhook.yaml
charts/cosigned/values.yaml

Fixes
```release-note
cosigned: Add flag to expose metrics to prometheus
```
This PR adds the configmap, service and service monitor needed to expose the metrics in Prometheus.

cosigned: add scripts to expose metrics to prometheus

---

.github/workflows/release.yml
.github/workflows/test.yml
charts/cosigned/Chart.yaml
charts/cosigned/values.yaml

- ci: update helm to 3.7.1
- cosigned: add some artifcathub annotations
Fixes
```release-note
NONE
```

cosigned: add some artifcathub annotations

---

charts/cosigned/Chart.yaml
charts/cosigned/README.md
charts/cosigned/templates/webhook/clusterrole_webhook.yaml
charts/cosigned/templates/webhook/webhook_mutating.yaml
charts/cosigned/values.yaml

cosigned: update to release v1.3.0
```release-note
cosigned: update to release v1.3.0
```

cosigned: update to release v1.3.0

---

charts/cosigned/Chart.yaml
charts/cosigned/values.yaml

- cosigned: update chart to use cosigned version 1.3.1
n/a
```release-note
cosigned: update chart to use cosigned version 1.3.1
```

cosigned: update chart to use cosigned version 1.3.1

---

charts/cosigned/Chart.yaml
charts/cosigned/values.yaml

Update cosigned chart to use cosigned v1.4.0
Fixes
```release-note
cosigned: update chart to use cosigned version 1.4.0
```

cosigned: use cosigned version 1.4.0

---

charts/cosigned/Chart.yaml
charts/cosigned/values.yaml

update cosigned to v1.4.1
n/a
```release-note
update cosigned to v1.4.1
```

update cosigned to v1.4.1

---

.github/workflows/release.yml
.github/workflows/test.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
use pinned GA actions instead of version
Fixes
```release-note
feat: use pinned GA actions instead of version
```

feat: use pinned GA actions instead of version

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

- rekor: bump to release v0.4.0
n/a
```release-note
rekor: bump to release v0.4.0
```

rekor: bump to release v0.4.0

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

- update rekor chart to use rekor release v0.5.0
n/a
```release-note
update rekor chart to use rekor release v0.5.0
```

update rekor chart to use rekor release v0.5.0

---

charts/cosigned/Chart.yaml
charts/cosigned/README.md
charts/cosigned/templates/webhook/role_webhook.yaml
charts/cosigned/templates/webhook/rolebinding_webhook.yaml
charts/cosigned/values.yaml

Fix cosigned chart documentation w.r.t. namespace selection and update to v1.5.2
Fixes #53
```release-note
The cosigned version have bee updated to v1.5.2.
```

Fix cosigned chart documentation w.r.t. namespace selection and update to v1.5.2

---

charts/ctlog/Chart.yaml

Bumping ctlog chart in preparation for staged scaffolding release

Bump ctlog chart

---

charts/fulcio/Chart.yaml

Bump fulcio chart.
Requires #70 to be released first

Bump fulcio chart

---

charts/ctlog/Chart.yaml

bump ctlog to get the release over the automation
n/a
```release-note
NONE
```

bump ctlog to get the release over the automation

---

charts/fulcio/Chart.yaml

- bump fulcio to get the release over the automation
after #72 got merged
n/a
```release-note
NONE
```

bump fulcio to get the release over the automation

---

charts/ctlog/Chart.yaml

Corrected image in artifacthub definition

Corrected issues in ctlog artifacthub

---

charts/fulcio/Chart.yaml

Bumping fulcio chart for ctlog version update

Bump fulcio chart for ctlog

---

.github/workflows/test.yml
charts/rekor/Chart.yaml
ct-install.yaml

Updates to the rekor chart to align with version updates

Updates to rekor chart

---

charts/scaffold/Chart.yaml

Bumping versions of scaffold chart for all dependencies

Bumped scaffold versioning

---

charts/scaffold/Chart.yaml

bump scaffolding for rekor 0.2.16

---

charts/fulcio/Chart.yaml

bump fulcio version for dependency version.

---

charts/rekor/Chart.yaml

bump rekor ver for trillian version.

---

charts/fulcio/Chart.yaml

bump fulcio to sync dependencies

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Add option to specify signer type for Rekor
Fixes
```release-note
```

Add option to specify signer type for Rekor

---

charts/trillian/Chart.yaml
charts/trillian/templates/_helpers.tpl
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

also remove leading blank line for annotations.
Fixes
```release-note
```

Fix container port typo and logic for Trillian.

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.yaml

allow specifying securityContext for createtree job.
Fixes
```release-note
```

allow specifying securityContext for createtree job.

---

charts/scaffold/Chart.yaml

bump scaffold version for new rekor/fulcio version

---

charts/scaffold/Chart.yaml

Pick up new
- CT Log 0.2.5
- Fulcio 0.2.7
- Rekor 0.2.24
- Trillian 0.1.3
Fixes
```release-note
```

Bump scaffold ver for new dep ver.

---

charts/trillian/Chart.yaml
charts/trillian/values.yaml

The tag should be "1.29.0", not "1.29"
Fixes
```release-note
```

fix gcp cloud proxy image tag.

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.yaml

Needed for adding prometheus annotationt to scrap metrics.
Fixes
```release-note
```

Plumb pod annotations for ctlog.

---

charts/ctlog/Chart.yaml
charts/ctlog/values.yaml

Fixes
partial fix to https://github.com/sigstore/helm-charts/issues/110
```release-note
```

use latest ctlog, createctconfig and createcert images.

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

Fixes
partial fix to #110 
```release-note
```

use latest fulcio and createcert images.

---

charts/fulcio/Chart.yaml

pick up new ctlog 0.2.7 for fulcio

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/values.yaml

fulcioURL flag defined here, https://github.com/sigstore/scaffolding/blob/main/cmd/ctlog/createctconfig/main.go#L57
Swap createtree/createctconfig digest to correct one.
Fixes
```release-note
```

Allow specifying Fulcio URL to createctconfig job.

---

charts/ctlog/Chart.yaml
charts/ctlog/values.yaml

createtree|createctconfig image got swapped.

---

charts/fulcio/Chart.yaml

bump fulcio to pick up ctlog 0.2.9

---

charts/rekor/Chart.yaml
charts/rekor/templates/_helpers.tpl

Fix ingress port to reference correct port

Fix ingress port

---

charts/scaffold/Chart.yaml

and Rekor 0.2.25
Fixes
```release-note
```

bump scaffold to pickup fulcio 0.2.10, ctlog 0.2.9

---

.gitignore
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-configmap.yaml
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

Adds support for the recently added `kmsca` backend in Fulcio
```release-note
* Added support for `kmsca` backend in Fulcio
```

Fulcio: Add support for kmsca backend

---

charts/trillian/Chart.yaml
charts/trillian/values.yaml

bump trillian for new images.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl
charts/ctlog/templates/ctlog-ingress.yaml
charts/ctlog/values.yaml

Add ingress for ctlog helm.

---

charts/ctlog/Chart.yaml
charts/ctlog/values.yaml

bump ctlog for new createtree image.

---

charts/scaffold/Chart.yaml

fulcio 0.2.10 -> 0.2.11
rekor 0.2.25 -> 0.2.26
trillian 0.1.5 -> 0.1.6
ctlog 0.2.9 -> 0.2.11
Fixes
```release-note
```

bump dependency versions for scaffold.

---

charts/scaffold/Chart.yaml

bump scaffold to pick up fix in rekor chart.

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml

same fix #137, but for volumemount

---

charts/scaffold/Chart.yaml

bump scaffold to pick up fix #2 in rekor chart.

---

charts/cosigned/Chart.yaml
charts/cosigned/values.schema.json

Regenerate values schema for cosigned chart following the steps described in https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/. 
Fixes
```release-note
NONE
```

[cosigned] Regenerate values schema

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/ci/ci-values.yaml
charts/fulcio/templates/_helpers.tpl
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/templates/fulcio-grpc-ingress.yaml
charts/fulcio/templates/fulcio-http-ingress.yaml
charts/fulcio/values.yaml

This is a breaking change, as it adds another level for ingress, http
and grpc.
I am open to making it backwards compatible by keeping the http settings
at the same level, and have all of the grpc settings one level deeper.
The downside to this is it makes it messier having a mix of settings.
Fixes
```release-note
```

Add support for grpc in fulcio.

---

charts/fulcio/Chart.yaml
charts/fulcio/templates/createcerts-job.yaml
charts/fulcio/values.yaml

- Add default securityContext.runAsUser value for fulcio
- Fix secret name for createcerts-job
**Checklist**

Fulcio securityContext and createcerts-job fixes

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

update fulcio with 0.4.0 release.

---

charts/scaffold/Chart.yaml
charts/scaffold/values.yaml

Remove unused value in values.yaml.
fulcio.fullnameOverride is not used, it should be
fulcio.server.fullnameOverride which was corrected in #148
**Checklist**

Bump scaffold version to pick up dep chart releases.

---

charts/fulcio/Chart.yaml
charts/fulcio/templates/fulcio-deployment.yaml

fileca if clause was covering kmsca when it shouldnt be.
**Checklist**

fix proper if/end clause.

---

charts/scaffold/Chart.yaml

bump scaffold for fulcio chart 0.3.3 for if/end fix.

---

charts/cosigned/Chart.yaml
charts/cosigned/values.yaml

Bump cosigned version to v1.8.0
**Checklist**

cosigned: bump version to v1.8.0

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

- update fulcio to use release v0.4.1
**Checklist**

update fulcio to use release v0.4.1

---

charts/scaffold/Chart.yaml

bump scaffold chart for fulcio app 0.4.1

---

charts/sigstore-prober/.helmignore
charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/_helpers.tpl
charts/sigstore-prober/templates/deployment.yaml
charts/sigstore-prober/templates/namespace.yaml
charts/sigstore-prober/templates/sa.yaml
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

**Checklist**
- [x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). Where applicable, update and bump the versions in any associated umbrella chart
- [ x] Variables are documented in the `values.yaml` and added to the README.md. THe [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use `helm-doc --dry-run` to preview the content
- [ x] JSON Schema generated
- [ x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command

Add in a helm chart for the sigstore prober

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl
charts/ctlog/templates/ctlog-ingress.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Simplify the logic in the template by only supporting k8s 1.19+ schema of
ingress.
1.18 EOL was 2021-06-18
1.19 EOL was 2021-10-28
1.20 EOL was 2022-02-28
Add support for ingressClassName field.
Will follow up with equivalent change to Rekor and Fulcio after this lands.
**Checklist**
- [ x ] Variables are documented in the `values.yaml` and added to the README.md. THe [helm-docs](https://github.com/norwoodj/helm-docs) utility can be used to generate the necessary content. Use …

only support k8s 1.19+ ingress schema.

---

charts/trillian/Chart.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

have trillian logserver/logsigner read db info the same way.

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/ci/ci-values.yaml
charts/fulcio/templates/_helpers.tpl
charts/fulcio/templates/fulcio-grpc-ingress.yaml
charts/fulcio/templates/fulcio-http-ingress.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

Simplify the logic in the template by only supporting k8s 1.19+ schema of
ingress.
1.18 EOL was 2021-06-18
1.19 EOL was 2021-10-28
1.20 EOL was 2022-02-28
Add support for ingressClassName field.
**Checklist**

only support k8s 1.19+ ingress schema for fulcio

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/ci/ci-values.yaml
charts/rekor/templates/_helpers.tpl
charts/rekor/templates/server/ingress.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Simplify the logic in the template by only supporting k8s 1.19+ schema of
ingress.
1.18 EOL was 2021-06-18
1.19 EOL was 2021-10-28
1.20 EOL was 2022-02-28
Add support for ingressClassName field.
**Checklist**

only support k8s 1.19+ ingress schema for rekor.

---

charts/fulcio/Chart.yaml

Dependency alignment for Fulcio chart
**Checklist**

Align fulco dependencies

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

- bump rekor server to use release v0.7.0
**Checklist**

bump rekor server to use release v0.7.0

---

charts/trillian/Chart.yaml
charts/trillian/values.yaml

curl: 7.81.0 -> 7.83.1
netcat: 2022-01-23 -> 2022-05-23
db_server: 1.4.0 -> 1.4.1
trillian_log_server: 646d069f3cb996b6c0e66223404ddecf08822823 -> rekor v0.7.0
trillian_log_signer: 646d069f3cb996b6c0e66223404ddecf08822823 -> rekor v0.7.0
**Checklist**

bump image versions used in trillian chart.

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

allow specifying ctlog log prefix in fulcio.
also bump up ctlog version.
**Checklist**

allow specifying ctlog log prefix in fulcio.

---

charts/scaffold/Chart.yaml

next fulcio and rekor chart are breaking changes. so one more before picking those up.
**Checklist**

bump scaffold one more time before breaking changes.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/values.schema.json
charts/scaffold/values.yaml

Account for `logPrefix` in scaffolding
None
None
**Checklist**

Specify the logPrefix for ctlog

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/ctlog-deployment.yaml

to ensure deployment will always use the latest configmap.
following https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
@nsmith5 PTAL
**Checklist**

have ctlog deployment rollout with configmap change.

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml

to ensure deployment will always use the latest configmap.
following https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
@nsmith5 PTAL
**Checklist**

have rekor deployment rollout with configmap change

---

charts/scaffold/Chart.yaml

will wait for rekor release before merging.
**Checklist**

bump scaffold chart dep versions.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.schema.json
charts/ctlog/values.yaml
charts/fulcio/Chart.yaml

ctlog 0.2.19 -> 0.2.22
this requires #204
**Checklist**

update fulcio with new ctlog chart version

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/createctconfig-job.yaml

missing colon for ctlog createctconfig job

---

charts/scaffold/Chart.yaml

Depends on merging #208 and #207 
**Checklist**

bump scaffold for new fulcio/ctlog chart

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

Added init container to wait for createtree job to finish
None
None
**Checklist**

ctlog init container

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart with 0.8.1 release

---

charts/fulcio/Chart.yaml

bump fulcio to fix release chart

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/crds/clusterimagepolicy.yaml

Knative code checks if the conversion has been configured at webhook level 
https://github.com/knative/pkg/blob/88d453618285d35152f87480d383508bb769bb2f/webhook/resourcesemantics/conversion/reconciler.go#L85
Closes #https://github.com/sigstore/helm-charts/issues/218
**Checklist**

fix: webhook crd conversion error

---

charts/scaffold/Chart.yaml

bump scaffold with new rekor

---

.github/workflows/release.yml
.github/workflows/test.yml

- pin actions to a github commit
- update helm to v3.9.0
**Checklist**

pin to github commit and update helm

---

charts/scaffold/Chart.yaml

- update rekor dependencie due rekor release v0.8.2
need: https://github.com/sigstore/helm-charts/pull/229
**Checklist**

update rekor dependencie due rekor release v0.8.2

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

- update rekor chart to use release v0.9.0
**Checklist**

update rekor chart to use release v0.9.0

---

charts/scaffold/Chart.yaml

- bump rekor deps
xref: #235 
**Checklist**

bump rekor deps

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

- bump rekor to v0.9.1 release
**Checklist**

bump rekor to v0.9.1 release

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

- bump fulcio to v0.5.1 release
**Checklist**

bump fulcio to v0.5.1 release

---

charts/scaffold/Chart.yaml

update scafolding to get latest releases of fulcio and rekor
**Checklist**

update scafolding to get latest releases of fulcio and rekor

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/webhook/webhook_mutating.yaml

Set reinvocationPolicy to 'IfNeeded' for the tag resolver webhook. This is needed when other mutating webhooks alter pod spec, e.g. inject a sidecar container, and result into images using tags.
ref: https://sigstore.slack.com/archives/C01PZKDL4DP/p1657691580474789
**Checklist**

Set reinvocationPolicy to 'IfNeeded' for the tag resolver webhook

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

- update fulcio to v0.5.2
n/a
n/a
**Checklist**

update fulcio to v0.5.2

---

charts/scaffold/Chart.yaml

- update fulcio dependency in scaffolding chart
**Checklist**

update fulcio dependency in scaffolding chart

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/values.yaml

Bump policy-controller to pull the latest version from its new repository v0.2.0
**Checklist**

switch policy-controller to latest v0.2.0

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

- update rekor chart to use release v0.10.0
**Checklist**

update rekor chart to use release v0.10.0

---

charts/scaffold/Chart.yaml

- bump rekor dependency
**Checklist**

bump rekor dependency

---

charts/policy-controller/Chart.yaml
charts/policy-controller/values.yaml

- update policy controller to use release v0.2.1
**Checklist**

update policy controller to use release v0.2.1

---

charts/scaffold/Chart.yaml

Update scaffold chart with trillian 0.1.9

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/values.yaml

Update sigstore-prober to latest image

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

depends on https://github.com/sigstore/helm-charts/pull/260

Add option to specify admin_server for createtree Job in rekor

---

charts/rekor/Chart.yaml
charts/rekor/templates/server/deployment.yaml

similar to https://github.com/sigstore/helm-charts/pull/195/files
**Checklist**

rollout rekor deployment if sharding configmap changes

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/ci/ci-values.yaml
charts/updatetree/templates/job.yaml
charts/updatetree/values.schema.json
charts/updatetree/values.yaml

Add enabled option to updatetree

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

- update rekor-server image to v0.11.0
**Checklist**

update rekor-server image to v0.11.0

---

charts/scaffold/Chart.yaml

- update rekor dependency
**Checklist**

update rekor dependency

---

charts/fulcio/Chart.yaml
charts/fulcio/values.yaml

- bump fulcio image to use release v0.5.3
**Checklist**

bump fulcio image to use release v0.5.3

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/ci/ci-values.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.schema.json
charts/rekor/values.yaml

Corrected values and schema for Rekor chart
**Checklist**

Corrected rekor schema issue

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

Update rekor helm chart to rekor v0.12.0

---

charts/scaffold/Chart.yaml

Update scaffold chart version to include new rekor version

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

closes https://github.com/sigstore/helm-charts/issues/289
**Checklist**

Revert rekor back to v0.11.0

---

charts/scaffold/Chart.yaml

Bump scaffolding to include new rekor

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

- update rekor image to v0.12.0 release
**Checklist**

update rekor image to v0.12.0 release

---

README.md

Updates the list of charts on the repository README

Update chart listing

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor server to v0.12.1

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/values.yaml

Update for v0.4.8

---

charts/updatetree/Chart.yaml
charts/updatetree/templates/job.yaml
charts/updatetree/values.schema.json
charts/updatetree/values.yaml

similar update that was made in this PR #315

[updateTree] add job extra annotations

---

charts/fulcio/Chart.yaml
charts/fulcio/templates/createcerts-job.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

similar update that was made in this PR #315

[Fulcio] add job extra annotations

---

charts/ctlog/Chart.yaml
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/createtree-job.yaml
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

similar update that was made in this PR #315

[CTLog] add job extra annotations

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

Signed-off-by: Meredith Lancaster <malancas@github.com>
Update Rekor chart to use release v0.12.2

Update Rekor chart to use release v0.12.2

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/values.yaml

Update prober for new verification correctness checking.

Update prober  to 0.4.9

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

we need this to close out one of the remaining items in https://github.com/sigstore/public-good-instance/issues/387

add --log_type flag to fulcio to enable production logging

---

charts/scaffold/Chart.yaml

Bump scaffold version to latest fulcio release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

Signed-off-by: Simon Kent <simek@google.com>

Bump sigstore-prober version and wire "slo-endpoint" field.

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/README.md.gotmpl
charts/fulcio/values.yaml
ct.yaml

- Allow committing Chart.lock, exclude charts/*.tgz
- Pin fulcio dependency versions
- Add fulcio README.md.gotmpl and generate docs
#298 
**Checklist**

pin fulcio deps

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Update Fulcio helm chart for prerelease

---

charts/scaffold/Chart.yaml

Signed-off-by: Hayden B <hblauzvern@google.com>

Update scaffold helm chart for Fulcio RC

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Update rekor release to 1.0 prerelease

---

charts/rekor/Chart.yaml

Update rekor chart version to the rc.1

---

charts/scaffold/Chart.yaml

Update scaffold chart to rekor rc

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/templates/policy-webhook/configmap-policy-controller.yaml
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Bump the policy-controller chart to use v0.4.0

Bump policy-controller to v0.4.0

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md

```
helm-docs -g charts/fulcio
```

update fulcio chart docs, with:

---

charts/rekor/Chart.yaml
charts/rekor/README.md

Break out the bumping of charts to sub PRs as suggested in #348 . This one bumps `rekor`
Grab the latest release version of createtree.
Use the latest version of Trillian chart.

bump rekor version, run code-gen

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md

bump policy-controller version, run helm-docs

bump policy-controller version.

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md

bump sigstore-prober version & run helm-docs

bump sigstore-prober.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/_helpers.tpl

In #348 I tried to add a new selector to match other components (namely, `component`), but this causes problems with
the existing deployments.
So drop it.

Remove the component from ctlog as this breaks existing ctlog selectors.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Pick up the change for: #355
bump scaffold release.

pick up latest ctlog, bump scaffold.

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Release Rekor 1.0

---

charts/scaffold/Chart.yaml

Bump up scaffold version to include Rekor 1.0

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Update Helm Chart for Fulcio 1.0.0

---

charts/scaffold/Chart.yaml

Bump scaffold for fulcio 1.0.0

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump ctlog to 0.2.30.

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml

the flags take in db & mysql_uri. Do not add db into the mysql_uri, it gets appended to mysql_uri by the code.

Fix createdb

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

use trillian 0.1.12 in scaffold chart, bump to 0.3.31

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createtree-job.yaml
charts/ctlog/values.yaml

Take in (rather than auto-construct) the display name used for the tree. Partly because it has a 20 char limit, partly to have more control over it.

Fix the displayname that was too long.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/values.yaml

Trillian tree display name must be <20 chars, pick up the ctlog chart that makes it customizable.

use ctlog-0.2.31 to pick up a fix for ctlog displayname.

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

Pick up the latest version for the createctconfig to pick up the -private-secret flag / logic for it.

latest image for createctconfig (scaffolding 0.4.12).

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Pick up 0.2.32 of ctlog for scaffolding 

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml

createctconfig used to have -namespace flag but it was removed, so having it failed to job from running.

remove -namespace flag that was dropped somewhere along the way.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

pick up ctlog 0.2.33 which removes -namespace flag from createctconfig.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Pick up the new ctlog changes because the config/certs are now managed differently.

pick up ctlog-0.2.34

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

fix capabilities `all` casing, should be `ALL`

fix capabilities casing

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

fix capabilities `all` casing, should be `ALL`

fix capabilities `all` casing

---

ct.yaml

Fix name of excluded chart

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

Bump policy-controller to latest version.

bump policy-controller v0.4.1

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/policy-webhook/configmap-policy-controller.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

The config map wasn't exposing any property in the values.yaml to set a different value for the configmap. 
closes https://github.com/sigstore/helm-charts/issues/407

support changing config-policy-controller configmap

---

charts/rekor/Chart.yaml
charts/rekor/values.yaml

bump rekor to v1.0.1

---

charts/scaffold/Chart.yaml

bump rekor in scaffolding deps

bump rekor in scaffolding deps

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Updated scaffold for latest TUF changes

Updated scaffold for latest changes for TUF

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bumped Fulcio in scaffolding

---

charts/scaffold/Chart.yaml

Bump scaffold version to include rekor and ctlog changes

---

charts/policy-controller/Chart.yaml

bump policy controller version for merge issue,
was missed in https://github.com/sigstore/helm-charts/pull/395 as it didnt rebase and update version.
0.3.7 already existed, it should have been 0.3.8

bump policy controller version for merge issue

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

Use the latest version of createctconfig (v0.5.2)
https://github.com/sigstore/scaffolding/pkgs/container/scaffolding%2Fcreatectconfig/54307469?tag=v0.5.2

Use the v0.5.2 version of createctconfig image.

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Update to use ctlog helm-chart 0.2.36. Note the README has additional changes because it appears to have been out of date.

Update ctlog to 0.2.36.

---

charts/scaffold/Chart.yaml

bump scaffold chart for ctlog
ctlog chart 0.2.27 -> 0.2.37

bump scaffold chart for ctlog

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold to 0.4.8, use ctlog 0.2.38.

use ctlog 0.2.38, cut scaffold 0.4.8

---

.github/workflows/release.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I noticed that release workflow uses Helm >= 3.8.x, so from 3.8.0 the OCI support is GA, we can remove the experimental environment variables for Helm

remove experimental oci env for helm CLI

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/README.md.gotmpl
charts/tsa/ci/ci-values.yaml
charts/tsa/templates/_helpers.tpl
charts/tsa/templates/namespace.yaml
charts/tsa/templates/tsa-configmap.yaml
charts/tsa/templates/tsa-deployment.yaml
charts/tsa/templates/tsa-http-ingress.yaml
charts/tsa/templates/tsa-service.yaml
charts/tsa/templates/tsa-serviceaccount.yaml
charts/tsa/values.schema.json
charts/tsa/values.yaml

Add TSA Helm chart

---

.github/workflows/release.yml

Adding cosign signing of charts

Added cosign signing of charts

---

.github/workflows/release.yml

Resolve an issue with capturing the digest of the pushed chart

Fix release process to capture digest

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/templates/deployment.yaml

Signed-off-by: Thomas Stromberg <t+github@chainguard.dev>
Adds resource limits to the sigstore prober:
Memory:
* Current prod usage: 22MiB
* New reservation: 64MiB (~3X)
* New limit: 128MiB (~6X)
CPU:
* Current prod usage: 2% of a core
* New reservation: 7.5% of a core (3.75X)
* New limit: 25% of a core (10X)
Fixes https://github.com/sigstore/public-good-instance/issues/1116
To compare against historical CPU and memory usage, see https://console.cloud.google.com/kubernetes/deployment/us-central1/sigstore-prod/sigstore-prober/sigstore-prober/overview?project=project-rekor

Add resource limits for the sigstore prober

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Bump policy-controller version to v0.5.2

Bump policy-controller version to v0.5.2

---

charts/trillian/Chart.yaml
charts/trillian/values.schema.json
charts/trillian/values.yaml

Signed-off-by: Bob Callaway <bcallaway@google.com>

bump cloudsql proxy to v1.33.1

---

charts/rekor/Chart.yaml
charts/rekor/README.md

Signed-off-by: Bob Callaway <bcallaway@google.com>

bump rekor chart to use latest version of trillian chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Signed-off-by: Bob Callaway <bcallaway@google.com>

bump scaffold to use latest rekor, trillian charts

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

continuation of the work from #455

update trillian in scaffold chart

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

Update sigstore-prober to use latest release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.schema.json
charts/trillian/values.yaml

- update createdb to use release v0.6.1

update createdb to use release v0.6.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump trillian chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Pick up scaffolding 0.2.40 from #471.

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Add support for self-signed CAs in `policy-controller`
Closes https://github.com/sigstore/policy-controller/issues/52
```
Linting chart "policy-controller => (version: \"0.4.0\", path: \"charts/policy-controller\")"
Checking chart "policy-controller => (version: \"0.4.0\", path: \"charts/policy-controller\")" for a version bump...
Old chart version: 0.3.9
New chart version: 0.4.0
Chart version ok.
Validating /Users/elfotografo007/git/helm-charts/charts/policy-controller/Chart.yaml...
Validation success! 👍
Linting chart with values file "charts/policy-controller/ci/ci-values.yaml"...
==> Linting charts/policy-controller
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------- …
```

Add support for self-signed CAs in `policy-controller`

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Update scaffold chart for fulcio 1.1.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/values.schema.json
charts/scaffold/values.yaml

Update scaffold chart for TSA

---

.github/workflows/release.yml

related to https://github.com/sigstore/helm-charts/issues/484

Add COSIGN_YES env var

---

charts/policy-controller/Chart.yaml
charts/policy-controller/templates/crds/clusterimagepolicy.yaml

This MR adds namespace templating to CRD to allow to change namespace for HELM installation
- [?] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

add namespace for conversion webhook

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/webhook/webhook_mutating.yaml
charts/policy-controller/templates/webhook/webhook_validating.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

Expose the failurePolicy as a configurable property

Configure the failure policy value

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Update Fulcio chart to 1.2.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Update scaffold for Fulcio 1.2.0

---

charts/scaffold/Chart.yaml
charts/scaffold/README.md
charts/scaffold/values.yaml

TSA is not something that every deployment needs

Change TSA enabled to disabled by default

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

update rekor chart in scaffold chart to v1.3.0

update rekor chart in scaffold chart to v1.3.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump rekor version in scaffold v1.3.1
Fix #499

chore(cd): bump rekor chart version for scaffold

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/templates/tsa-deployment.yaml

This PR was merged 5 months ago and changed the argument `log_type` to `log-type` and helm charts is still using the old one.
https://github.com/sigstore/timestamp-authority/commit/fa7f6bb96424c8d60b3f377e95d337d62354abae#diff-deeb4d2a36a96a0255e71d935b96ee7d53cc5b4eb58cbc4a961d859fcdf3af60R59

fix(tsa): Fix log type argument

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Signed-off-by: Cody Soyland <codysoyland@github.com>
Updating the Fulcio chart to version 1.3.0

Update Fulcio chart to 1.3.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Signed-off-by: Cody Soyland <codysoyland@github.com>

Update scaffold for Fulcio 1.3.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

This only adds #520, a config fix for the Fulcio chart.

Bump Fulcio in scaffold chart

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump chart to latest version of rekor

bump rekor to v1.1.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

update rekor chart in scaffold chart to v1.3.2

update rekor chart in scaffold chart to v1.3.2

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffolding for new rekor release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml

- update scaffold to get trillian updates
trillian chart update in #551 
Related to https://github.com/sigstore/public-good-instance/issues/1430

update scaffold to get trillian updates

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/ctlog-deployment.yaml

Adds the helm.sh/chart label to ctlog pods so that that label will be persisted into metrics for the purpose of creating a dashboard for the current versions of services running. See https://github.com/sigstore/public-good-instance/issues/714

Adding helm chart label to ctlog pods

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold for ctlog 0.2.43

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for new version

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold for rekor bump

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump fulcio version in scaffold chart

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/ci/ci-values.yaml
charts/fulcio/templates/fulcio-backendconfig.yaml
charts/fulcio/templates/fulcio-frontendconfig.yaml
charts/fulcio/templates/fulcio-ingress.yaml
charts/fulcio/templates/fulcio-service.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

add parallel ingress to fulcio chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for fulcio w/ parallel ingress

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffolding chart for rekor fix

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/templates/fulcio-deployment.yaml
charts/fulcio/templates/fulcio-service.yaml
charts/fulcio/templates/namespace.yaml
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

bump fulcio to v1.3.3; add extraArgs and ns labels to chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for new fulcio chart

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Increases appVersion for new 1.3.4 release

bump fulcio chart for v1.3.4

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold for v1.3.4 fulcio release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for ctlog 0.2.44

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

- update trillian chart in scaffold
to get https://github.com/sigstore/helm-charts/pull/578
Related to https://github.com/sigstore/public-good-instance/issues/1534

update trillian chart in scaffold

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump Fulcio chart for 1.4.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for Fulcio 1.4.0

---

charts/policy-controller/Chart.yaml
charts/policy-controller/values.yaml

Signed-off-by: anderssonw <wandersson.98@gmail.com>

bump controller to v0.8.2

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for trillian 0.2.9 chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor 1.3.7

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

export startup probe on deployments, all probes on cloud-sql-proxy

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart to 0.6.25 to pick up latest trillian

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/createdb/createdb-job.yaml

fix command line args on createdb job

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump scaffolding deps on trillian chart

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.schema.json
charts/tuf/values.yaml

bump tuf chart for scaffolding v0.6.7

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.schema.json
charts/rekor/values.yaml

bump rekor for scaffolding v0.6.7

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.schema.json
charts/ctlog/values.yaml

bump ctlog chart for scaffolding v0.6.7

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.schema.json
charts/fulcio/values.yaml

bump fulcio chart for scaffolding v0.6.7

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for scaffolding v0.6.7

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold for trillian 0.2.13

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

use :latest for kubectl

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart to latest scaffolding release, c-s-p version

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for new trillian chart

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v1.3.1

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump fulcio chart for 1.4.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for rekor 1.3.1 and fulcio 1.4.1

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/README.md.gotmpl
charts/tsa/values.yaml

Update TSA chart to 1.2.0

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Update to Rekor 1.3.2

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump Fulcio for 1.4.3

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for Rekor 1.3.2, Fulcio 1.4.3, TSA 1.2.0

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/deployment.yaml
charts/sigstore-prober/values.yaml

bump sigstore-prober chart to latest version, add securityContext

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/deployment.yaml

move securityContext out of if clause

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/templates/createctconfig-job.yaml
charts/ctlog/templates/createtree-job.yaml
charts/ctlog/templates/ctlog-deployment.yaml
charts/ctlog/values.yaml

update ctlog chart to latest scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/backfillredis/backfill-job.yaml
charts/rekor/templates/redis/deployment.yaml
charts/rekor/templates/server/createtree-job.yaml
charts/rekor/templates/server/deployment.yaml
charts/rekor/values.yaml

add containerSecurityContext to rekor chart

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for securityContext fields

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for dep update

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for trillian/scaffolding releases

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for scaffolding v0.6.9 release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for v0.6.9 scaffolding release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for scaffolding v0.6.9 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for scaffolding v0.6.9

---

.github/workflows/test.yml

bump chart-testing-action

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump containers to trillian v1.5.3 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump containers for rekor v1.3.3 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for trillian, rekor releases

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for scaffolding 0.6.10 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for 0.6.10 release

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for 0.6.10

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian for 0.6.10 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor for 0.6.10

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio for 0.6.10

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for 0.6.10

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/_helpers.tpl
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

policy-controller: add custom labels

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/_helpers.tpl
charts/policy-controller/templates/webhook/deployment_webhook.yaml
charts/policy-controller/values.schema.json
charts/policy-controller/values.yaml

policy-controller :::: fix: remove duplicated labels

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v1.3.4 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

Bump the sigstore-prober to get the latest changes from scaffolding

bump prober chart for scaffolding to v0.6.12

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

Bump TSA to v1.2.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for TSA

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

upgrade cloud-sql-proxy to v2.8.1, curl to v8.5.0, createdb to v0.6.14

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for updated trillian chart, other deps

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog for latest scaffolding release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

update updatetree chart for latest scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/backfillredis/backfill-job.yaml
charts/rekor/templates/server/createtree-job.yaml

Signed-off-by: Karl Haworth <karl.haworth@aa.com>
Add missing rekor imagePullSecrets
`createtree-job.yaml` and `backfill-job.yaml` both need image pull secrets if pulling from a private source.
N/A
Similar to https://github.com/sigstore/helm-charts/pull/677
Following the existing pattern from other charts, add image pull secrets for private registries.

Add missing rekor imagePullSecrets

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart to v1.6.0 release

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for scaffolding v0.6.16 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf to scaffolding v0.6.16 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober to scaffolding v0.6.16 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for scaffolding v0.6.16 release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for scaffolding v0.6.16 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.6.16 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor for v1.3.5 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold for rekor v1.3.5

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for 1.4.4 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for fulcio 1.4.4 release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for v0.6.17 scaffolding release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for scaffolding v0.6.17 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for v0.6.17 scaffolding release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for v0.6.17 scaffolding release

---

charts/scaffold/Chart.yaml
charts/scaffold/templates/clusterrole.yaml

Add patch permission on the role used in the 
Resolve #728

Add patch permissions on secrets

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Bump Rekor chart to v1.3.6

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for fulcio v1.4.5

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for rekor chart 1.4.0

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/templates/tsa-deployment.yaml
charts/tsa/values.schema.json
charts/tsa/values.yaml

```
tsa => (version: "1.0.3", path: "charts/tsa")
------------------------------------------------------------------------------------ …
```

adds tolerations, nodeSelector, and affinity to tsa.

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/mysql/deployment.yaml
charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/mysql/deployment.yaml
charts/trillian/templates/trillian-log-server/deployment.yaml
charts/trillian/templates/trillian-log-signer/deployment.yaml

Fixes https://github.com/sigstore/helm-charts/issues/738

Clean up duplicate keys in trillian and rekor

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

Also update docs missing from last version bump.

Bump sigstore-prober version

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump Fulcio to v1.5.0

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for Fulcio v1.5.0

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump fulcio chart to v1.5.1

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/server/createtree-job.yaml

completely closes https://github.com/sigstore/helm-charts/issues/696
adds tolerations, nodeSelector, and affinity to createtree-job.
- https://github.com/sigstore/helm-charts/issues/696
- [original pull request](https://github.com/sigstore/helm-charts/pull/762)
```
rekor => (version: "1.4.4", path: "charts/rekor")
"sigstore" already exists with the same configuration, skipping
Hang tight …
```

adds tolerations, nodeSelector, and affinity to rekor/templates/server/createtree-job.yaml

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for latest scaffolding release

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

bump tsa chart for 1.2.2 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump sigstore-prober chart for 0.7.5 scaffolding release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for 0.7.5 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for 0.7.5 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for scaffolding 0.7.5 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bumping fulcio for scaffolding

Bump fulcio for scaffolding

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

It moves the fulcio image to the release 1.6.0 and bumps chart version
cc @haydentherapper

Upgrade fulcio image and bump version

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio to 1.6.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump fulcio for scaffold

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio to 1.6.2

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold. fulcio to 1.6.2

bump scaffold. fulcio to 1.6.2

---

CONTRIBUTING.md

It updates the contribution doc adding a section about how to test the helm charts locally.

update contributing doc adding how to test helm charts locally

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for scaffolding v0.7.8 release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for trillian v1.6.1, scaf 0.7.8 releases

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for scaffolding v078 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for scaffolding v0.7.8 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.7.8 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

- bump scaffold to have fulcio v1.6.4 release

bump scaffold to have fulcio v1.6.4 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/templates/_helpers.tpl
charts/sigstore-prober/values.schema.json
charts/sigstore-prober/values.yaml

specify grpc endpoint in sigstore-prober chart

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober to v0.7.9 scaffolding release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for v0.7.11 scaffolding release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for v0.7.11 scaffolding release

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

bump tsa chart for timestamp-server v1.2.3 release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for v0.7.11 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.7.11 scaffolding release

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart to incorporate copy-secret changes

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump deps for ctlog chart

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for scaf 0.7.15 release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree for scaf 0.7.15 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for scaf 0.7.15 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for scaf 0.7.15 release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for scaf v0.7.15 releasE

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for scaf 0.7.15 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for scaf 0.7.15 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for multi-shard Rekor reads

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for v0.7.17 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for 1.3.7 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for new rekor release

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/values.yaml

Bump policy-controller to use v0.11.0

bump policy-controller to v0.11.0

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump chart for prober for scaf v0.7.18 release

---

.github/dependabot.yml

enable dpbot for bumping container refs in charts

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian for v1.7.0 (and v0.7.18 scaffolding) releases

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for v0.7.18 scaffolding release, fulcio v1.6.5

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for scaffolding v0.7.18 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.7.18 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v1.3.8 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor release

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

Bump TSA version to latest

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Bump rekor to v1.3.9

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold to pick up latest Rekor

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for recent fulcio release

---

charts/rekor/Chart.yaml
charts/rekor/README.md

Fix digest for rekor v1.3.9

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for 1.6.4 rekor chart

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/templates/_helpers.tpl

fix typo in rekor template

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor 1.6.5

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor/trillian bump

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio chart for v0.7.21 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v0.7.21 scaffolding release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober chart for v0.7.21 scaffolding release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for v0.7.21 scaffolding release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for v0.7.21 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.7.21 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for new tsa release

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/templates/tsa-deployment.yaml

tsa: make tink_hcvault_token optional if not using vault

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.schema.json
charts/rekor/values.yaml

There are no references to it within the chart so removing it

remove scaffoldSQLProxy from rekor chart

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for scaffolding v0.7.22 release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for scaffolding v0.7.22 release

---

charts/ctlog/Chart.yaml
charts/ctlog/README.md
charts/ctlog/values.yaml

bump ctlog chart for scaffolding v0.7.22 release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf chart for scaffolding v0.7.22 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

needs trillian chart to merge first

bump rekor chart for scaffolding v0.7.22 release

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml
charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

Bump Fulcio and Rekor to latest versions

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold chart for Fulcio v1.7.0 and Rekor v1.3.10

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Fix mistyped image version@digest

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold chart with Fulcio chart fix

---

.github/dependabot.yml

turn on new dependabot for helm

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

Bump Fulcio for v1.7.1

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold for fulcio v1.7.1

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober for v0.7.23 scaffolding release

---

charts/tuf/Chart.yaml
charts/tuf/README.md
charts/tuf/values.yaml

bump tuf for v0.7.23 scaffolding release

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree for v0.7.23 scaffolding release

---

charts/fulcio/Chart.lock
charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio for v0.7.23 scaffolding release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor for v0.7.23 scaffolding release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for v0.7.23 scaffolding release

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/templates/_helpers.tpl

Fix nil dereference error in rekor-tiles

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/templates/_helpers.tpl

Fix rekor-tiles signer args

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/templates/_helpers.tpl

Fix quote in rekor-tiles chart

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/templates/configmap.yaml

Fix tink keyset formatting

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

Bump TSA to v1.2.7

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

Bump scaffold chart to pick up TSA bump

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/values.yaml

Bump rekor-tiles helm chart to v0.1.1 release

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/values.yaml

Using an untagged release temporarily to verify if this resolves the gRPC issue.

Bump rekor-tiles chart to latest release

---

charts/rekor-tiles/Chart.yaml
charts/rekor-tiles/README.md
charts/rekor-tiles/values.yaml

Bump rekor-tiles to v0.1.3

---

charts/tsa/Chart.yaml
charts/tsa/README.md
charts/tsa/values.yaml

Bump TSA to v1.2.8

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

bump updatetree chart for scaffolding v0.7.24 release

---

charts/sigstore-prober/Chart.yaml
charts/sigstore-prober/README.md
charts/sigstore-prober/values.yaml

bump prober for scaffolding v0.7.24 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor, trillian chart updates

---

charts/rekor/templates/_helpers.tpl

Add clarifying comment for setting redis hostname

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump chart for rekor v1.4.0 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart with rekor, trillian fixes

---

charts/policy-controller/Chart.yaml
charts/policy-controller/README.md
charts/policy-controller/templates/crds/clusterimagepolicy.yaml
charts/policy-controller/templates/crds/trustroots.yaml

Update Policy Controller CRD's to match `v0.13.0`
#1015

feat: update crds to match policy controller v0.13.0

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/templates/trillian-log-server/service.yaml
charts/trillian/templates/trillian-log-signer/service.yaml
charts/trillian/values.schema.json
charts/trillian/values.yaml

make change to headless not a breaking change for existing deployments

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v1.4.1 release

---

charts/rekor/Chart.yaml
charts/rekor/README.md
charts/rekor/values.yaml

bump rekor chart for v1.4.2 release

---

charts/scaffold/Chart.lock
charts/scaffold/Chart.yaml
charts/scaffold/README.md

bump scaffold chart for rekor release typo

---

charts/updatetree/Chart.yaml
charts/updatetree/README.md
charts/updatetree/values.yaml

update updatetree chart for v0.7.25 release

---

charts/trillian/Chart.yaml
charts/trillian/README.md
charts/trillian/values.yaml

bump trillian chart for 0.7.25 release

---

charts/fulcio/Chart.yaml
charts/fulcio/README.md
charts/fulcio/values.yaml

bump fulcio for scaffolding v0.7.25 release
